/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NorgramRouteImport } from './routes/norgram'
import { Route as MusicDiscCardRouteImport } from './routes/music-disc-card'
import { Route as DummyRouteImport } from './routes/dummy'
import { Route as IndexRouteImport } from './routes/index'

const NorgramRoute = NorgramRouteImport.update({
  id: '/norgram',
  path: '/norgram',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicDiscCardRoute = MusicDiscCardRouteImport.update({
  id: '/music-disc-card',
  path: '/music-disc-card',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyRoute = DummyRouteImport.update({
  id: '/dummy',
  path: '/dummy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/music-disc-card': typeof MusicDiscCardRoute
  '/norgram': typeof NorgramRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/music-disc-card': typeof MusicDiscCardRoute
  '/norgram': typeof NorgramRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
  '/music-disc-card': typeof MusicDiscCardRoute
  '/norgram': typeof NorgramRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dummy' | '/music-disc-card' | '/norgram'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dummy' | '/music-disc-card' | '/norgram'
  id: '__root__' | '/' | '/dummy' | '/music-disc-card' | '/norgram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DummyRoute: typeof DummyRoute
  MusicDiscCardRoute: typeof MusicDiscCardRoute
  NorgramRoute: typeof NorgramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/norgram': {
      id: '/norgram'
      path: '/norgram'
      fullPath: '/norgram'
      preLoaderRoute: typeof NorgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-disc-card': {
      id: '/music-disc-card'
      path: '/music-disc-card'
      fullPath: '/music-disc-card'
      preLoaderRoute: typeof MusicDiscCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy': {
      id: '/dummy'
      path: '/dummy'
      fullPath: '/dummy'
      preLoaderRoute: typeof DummyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DummyRoute: DummyRoute,
  MusicDiscCardRoute: MusicDiscCardRoute,
  NorgramRoute: NorgramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
