/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DummyRouteImport } from './routes/dummy'
import { Route as IndexRouteImport } from './routes/index'

const DummyRoute = DummyRouteImport.update({
  id: '/dummy',
  path: '/dummy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dummy': typeof DummyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dummy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dummy'
  id: '__root__' | '/' | '/dummy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DummyRoute: typeof DummyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dummy': {
      id: '/dummy'
      path: '/dummy'
      fullPath: '/dummy'
      preLoaderRoute: typeof DummyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DummyRoute: DummyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
